name: learn
on: [push]
jobs:
  runs-docs-differ:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: yarn install
      - run: yarn run-differ -m -s 1 -b https://react-spectrum.adobe.com/ -c https://react-spectrum.adobe.com/
